"""Finite causal-cone capacity bounds for explicitly local controlled networks.

The mathematical premise is a synchronous radius-one local update contract:
for a fixed globally supplied control word, information about the *initial*
configuration can move by at most one graph edge per round. Therefore every
focal response trace generated by words of length at most ``T`` factors through
the initial configuration on the radius-``T`` ball around the focal node.

This module does not attempt to infer locality from arbitrary transition code.
Instead it provides finite certificates for the graph/state-capacity consequence
of a separately declared local-update contract.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import log2, prod
from typing import Iterable


def _positive_int(value: int, name: str) -> None:
    if not isinstance(value, int) or isinstance(value, bool) or value < 1:
        raise ValueError(f"{name} must be a positive integer")


def _nonnegative_int(value: int, name: str) -> None:
    if not isinstance(value, int) or isinstance(value, bool) or value < 0:
        raise ValueError(f"{name} must be a non-negative integer")


def _normalize_adjacency(adjacency: Iterable[Iterable[int]]) -> tuple[tuple[int, ...], ...]:
    try:
        normalized = tuple(tuple(neighbors) for neighbors in adjacency)
    except TypeError as error:
        raise ValueError("adjacency must be an iterable of neighbor iterables") from error
    if not normalized:
        raise ValueError("adjacency must contain at least one node")
    node_count = len(normalized)
    for node, neighbors in enumerate(normalized):
        if len(set(neighbors)) != len(neighbors):
            raise ValueError("adjacency rows must not contain duplicate neighbors")
        for neighbor in neighbors:
            if not isinstance(neighbor, int) or isinstance(neighbor, bool):
                raise ValueError("neighbor indices must be integers")
            if not 0 <= neighbor < node_count:
                raise ValueError("neighbor index is outside the graph")
            if neighbor == node:
                raise ValueError("self loops are not allowed")
    for node, neighbors in enumerate(normalized):
        for neighbor in neighbors:
            if node not in normalized[neighbor]:
                raise ValueError("adjacency must describe an undirected graph")
    return normalized


def _normalize_state_cardinalities(
    state_cardinalities: Iterable[int],
    node_count: int,
) -> tuple[int, ...]:
    try:
        normalized = tuple(state_cardinalities)
    except TypeError as error:
        raise ValueError("state_cardinalities must be iterable") from error
    if len(normalized) != node_count:
        raise ValueError("state_cardinalities must contain one value per node")
    for index, cardinality in enumerate(normalized):
        _positive_int(cardinality, f"state_cardinalities[{index}]")
    return normalized


def radius_ball(
    adjacency: tuple[tuple[int, ...], ...],
    focal_node: int,
    radius: int,
) -> tuple[int, ...]:
    """Return the sorted graph ball around ``focal_node`` through ``radius`` edges."""
    normalized = _normalize_adjacency(adjacency)
    _nonnegative_int(radius, "radius")
    if not isinstance(focal_node, int) or isinstance(focal_node, bool) or not 0 <= focal_node < len(normalized):
        raise ValueError("focal_node is outside the graph")

    visited = {focal_node}
    frontier = {focal_node}
    for _ in range(radius):
        next_frontier: set[int] = set()
        for node in frontier:
            next_frontier.update(normalized[node])
        next_frontier.difference_update(visited)
        if not next_frontier:
            break
        visited.update(next_frontier)
        frontier = next_frontier
    return tuple(sorted(visited))


def maximum_degree_ball_size(maximum_degree: int, radius: int) -> int:
    """Universal size upper bound for a graph ball with maximum degree ``Delta``."""
    _nonnegative_int(maximum_degree, "maximum_degree")
    _nonnegative_int(radius, "radius")
    if maximum_degree == 0:
        return 1
    if maximum_degree == 1:
        return 1 if radius == 0 else 2
    if maximum_degree == 2:
        return 1 + 2 * radius
    return 1 + maximum_degree * (((maximum_degree - 1) ** radius - 1) // (maximum_degree - 2))


def minimum_degree_bounded_horizon(
    response_class_count: int,
    maximum_degree: int,
    local_state_bound: int,
) -> int | None:
    """Smallest universal ball radius able to hold the response classes.

    ``None`` means that no finite horizon can provide enough local-state
    capacity under the declared maximum-degree/state bound. This occurs, for
    example, when all local states are trivial, or when maximum degree zero/one
    makes the universal causal cone saturate before the requested class count.
    """
    _positive_int(response_class_count, "response_class_count")
    _nonnegative_int(maximum_degree, "maximum_degree")
    _positive_int(local_state_bound, "local_state_bound")

    if response_class_count <= local_state_bound:
        return 0
    if local_state_bound == 1:
        return None
    if maximum_degree == 0:
        return None
    if maximum_degree == 1:
        return 1 if response_class_count <= local_state_bound**2 else None

    radius = 0
    while local_state_bound ** maximum_degree_ball_size(maximum_degree, radius) < response_class_count:
        radius += 1
    return radius


@dataclass(frozen=True)
class LocalCausalConeCapacityCertificate:
    """Exact information capacity of one declared finite graph ball.

    Under the separate radius-one local-update premise, any focal response
    signature generated by words of length at most ``horizon`` factors through
    the initial local states on ``ball_nodes``. Hence no such response quotient
    can contain more than ``ball_configuration_capacity`` classes.
    """

    adjacency: tuple[tuple[int, ...], ...]
    state_cardinalities: tuple[int, ...]
    focal_node: int
    horizon: int
    required_response_classes: int

    @property
    def node_count(self) -> int:
        return len(self.adjacency)

    @property
    def maximum_degree(self) -> int:
        return max(len(neighbors) for neighbors in self.adjacency)

    @property
    def ball_nodes(self) -> tuple[int, ...]:
        return radius_ball(self.adjacency, self.focal_node, self.horizon)

    @property
    def ball_node_count(self) -> int:
        return len(self.ball_nodes)

    @property
    def ball_configuration_capacity(self) -> int:
        return prod(self.state_cardinalities[node] for node in self.ball_nodes)

    @property
    def ball_information_capacity_bits(self) -> float:
        return sum(log2(self.state_cardinalities[node]) for node in self.ball_nodes)

    @property
    def required_interface_bits(self) -> float:
        return log2(self.required_response_classes)

    @property
    def has_sufficient_local_capacity(self) -> bool:
        return self.required_response_classes <= self.ball_configuration_capacity

    def verify(self) -> bool:
        try:
            adjacency = _normalize_adjacency(self.adjacency)
            if adjacency != self.adjacency:
                return False
            cardinalities = _normalize_state_cardinalities(self.state_cardinalities, len(adjacency))
            if cardinalities != self.state_cardinalities:
                return False
            _nonnegative_int(self.horizon, "horizon")
            _positive_int(self.required_response_classes, "required_response_classes")
            if not isinstance(self.focal_node, int) or isinstance(self.focal_node, bool):
                return False
            if not 0 <= self.focal_node < len(adjacency):
                return False
            if self.ball_node_count < 1:
                return False
            if self.ball_configuration_capacity < 1:
                return False
            if self.has_sufficient_local_capacity != (
                self.required_response_classes <= self.ball_configuration_capacity
            ):
                return False
            if self.has_sufficient_local_capacity and (
                self.required_interface_bits > self.ball_information_capacity_bits + 1e-12
            ):
                return False
            return True
        except (TypeError, ValueError):
            return False


def certify_local_causal_cone_capacity(
    adjacency: Iterable[Iterable[int]],
    state_cardinalities: Iterable[int],
    focal_node: int,
    horizon: int,
    required_response_classes: int,
) -> LocalCausalConeCapacityCertificate:
    """Certify one finite graph-ball response-capacity calculation."""
    normalized_adjacency = _normalize_adjacency(adjacency)
    normalized_cardinalities = _normalize_state_cardinalities(
        state_cardinalities,
        len(normalized_adjacency),
    )
    certificate = LocalCausalConeCapacityCertificate(
        adjacency=normalized_adjacency,
        state_cardinalities=normalized_cardinalities,
        focal_node=focal_node,
        horizon=horizon,
        required_response_classes=required_response_classes,
    )
    if not certificate.verify():
        raise ValueError("declared local causal-cone capacity contract does not verify")
    return certificate


@dataclass(frozen=True)
class DegreeBoundedCausalConeCertificate:
    """Universal bounded-degree/local-state horizon capacity calculation."""

    maximum_degree: int
    local_state_bound: int
    horizon: int
    required_response_classes: int

    @property
    def universal_ball_node_bound(self) -> int:
        return maximum_degree_ball_size(self.maximum_degree, self.horizon)

    @property
    def universal_response_class_capacity(self) -> int:
        return self.local_state_bound ** self.universal_ball_node_bound

    @property
    def universal_information_capacity_bits(self) -> float:
        return self.universal_ball_node_bound * log2(self.local_state_bound)

    @property
    def required_interface_bits(self) -> float:
        return log2(self.required_response_classes)

    @property
    def minimum_required_horizon(self) -> int | None:
        return minimum_degree_bounded_horizon(
            self.required_response_classes,
            self.maximum_degree,
            self.local_state_bound,
        )

    @property
    def finite_sufficient_horizon_exists(self) -> bool:
        return self.minimum_required_horizon is not None

    @property
    def horizon_is_large_enough(self) -> bool:
        minimum = self.minimum_required_horizon
        return minimum is not None and self.horizon >= minimum

    def verify(self) -> bool:
        try:
            _nonnegative_int(self.maximum_degree, "maximum_degree")
            _positive_int(self.local_state_bound, "local_state_bound")
            _nonnegative_int(self.horizon, "horizon")
            _positive_int(self.required_response_classes, "required_response_classes")
            if self.universal_ball_node_bound < 1:
                return False
            if self.universal_response_class_capacity < 1:
                return False

            minimum = self.minimum_required_horizon
            if minimum is None:
                if self.horizon_is_large_enough:
                    return False
            else:
                if minimum < 0:
                    return False
                if self.local_state_bound ** maximum_degree_ball_size(self.maximum_degree, minimum) < self.required_response_classes:
                    return False
                if minimum > 0 and (
                    self.local_state_bound ** maximum_degree_ball_size(self.maximum_degree, minimum - 1)
                    >= self.required_response_classes
                ):
                    return False

            if self.horizon_is_large_enough != (
                self.required_response_classes <= self.universal_response_class_capacity
            ):
                return False
            return True
        except (TypeError, ValueError):
            return False


def certify_degree_bounded_causal_cone(
    maximum_degree: int,
    local_state_bound: int,
    horizon: int,
    required_response_classes: int,
) -> DegreeBoundedCausalConeCertificate:
    """Certify a universal degree/state causal-cone capacity calculation."""
    certificate = DegreeBoundedCausalConeCertificate(
        maximum_degree=maximum_degree,
        local_state_bound=local_state_bound,
        horizon=horizon,
        required_response_classes=required_response_classes,
    )
    if not certificate.verify():
        raise ValueError("declared bounded-degree causal-cone contract does not verify")
    return certificate


__all__ = [
    "radius_ball",
    "maximum_degree_ball_size",
    "minimum_degree_bounded_horizon",
    "LocalCausalConeCapacityCertificate",
    "certify_local_causal_cone_capacity",
    "DegreeBoundedCausalConeCertificate",
    "certify_degree_bounded_causal_cone",
]
